### ISSUE TITLE
Critical Damage not correct applied

### ISSUE THREAD

**Issue by skyly87** [Nevela-0/PF1-Automate-Damage#13]
Only the Automate Damage mod was active during retrospective testing.
If critical damage is applied, only the normal damage is applied to the character.
![image](https://github.com/user-attachments/assets/1e7f37ac-b375-47d4-9387-08acbf1c84bf)
From the picture, when I apply the damage, not the 15 damage, but the 7 damage from the normal attack is applied.

**Comment by skyly87** [comment]
I have created a video so that you can watch it yourself

https://github.com/user-attachments/assets/7b97684f-0368-4127-831e-7e25bdb68322

**Comment by Nevela-0** [comment]
Interesting, it might be related to localization.
Currently, the module doesn't support other languages fully.

**Comment by skyly87** [comment]
> Interesting, it might be related to localization. Currently, the module doesn't support other languages fully.

Ok, thats the point. If the game are english, i dont have any problems.
