### ISSUE TITLE
Silver DR broken?

### ISSUE THREAD

**Issue by kris21barb** [Nevela-0/PF1-Automate-Damage#15]
In my PF1 game version 10.7, we had a monster with DR 10 Good/Silver, doing the fight one of my players had enchantment 3 on his weapon but it did not ignore the DR. After the game me and another player did some testing, we tried putting the weapon to +5, giving it mithral or alchemical silver, they all failed to overcome the DR, so i thought maybe it was because good was a part of it so i removed that, still did not overcome the DR. When good was in there and we made the weapon good it overcame the DR just fine, so it seemed like Silver was a problem and enhancement bonus is maybe not working correctly.

**Comment by Nevela-0** [comment]
Yes, I became aware of it a few hours ago. Recent PF updates changed it. The next update is in the works.

**Comment by Nevela-0** [comment]
Fixed with v1.3
