### ISSUE TITLE
Hardness not being applied 

### ISSUE THREAD

**Issue by asdfng** [Nevela-0/PF1-Automate-Damage#17]
When applying damage to creatures with hardness, hardness doesn't appear to be included in calculation. ignoreHardness boolean flag was not set and ignoreHardness dictionary flag was at first not set, then intentionally set to zero. 

When using shift+click hardness is scene as an option to reduce damage but it's not auto applied. Is this intentional?
![image](https://github.com/user-attachments/assets/7f399485-4461-426e-95ce-12806b78447c)
![image](https://github.com/user-attachments/assets/8b098639-75b7-4ea4-9a4c-177bbeb79723)  

When applying damage by just clicking "apply damage" the full 15 points of damage is applied.

![Screenshot 2024-09-16 at 18 17 07](https://github.com/user-attachments/assets/6c8a8832-af4d-46e2-bd7a-10b244959f53)

Bite attack does not have either of the "ignoreHardness" flags in this situation.
If there's something I'm missing please let me know.

**Comment by Nevela-0** [comment]
I assume the target has nothing other than hardness?

**Comment by asdfng** [comment]
Correct
