### ISSUE TITLE
Healing doesn't work

### ISSUE THREAD

**Issue by glittermancer** [Nevela-0/PF1-Automate-Damage#3]
When I cast a spell that has damage type "Healing" it subtracts from the target's HP

Also when I type /heal 50 in the chat, the buttons don't do anything

**Comment by glittermancer** [comment]
(but I'm loving being able to apply elemental damage and have resistances automatically apply, so thank you for your work here!)

**Comment by Nevela-0** [comment]
Hey!
Thank you so much for helping out. I was aware the healing might be an issue since I focused mainly on the damage but in doing so I completely forgot about it (which is also why I wanted to release the module to the public).

I'll try to fix it for the next update along with other issues.

**Comment by Nevela-0** [comment]
Healing is added with v0.8.
Thank you!
