### ISSUE TITLE
Typing /heal ## in the chat is broken

### ISSUE THREAD

**Issue by glittermancer** [Nevela-0/PF1-Automate-Damage#5]
Thanks for the heal and heal half buttons!

This is a related issue - if you type /heal 50 it should give you a box with buttons to heal or heal half, and with your module enabled, those buttons do nothing.

![Screenshot 2024-05-12 172239](https://github.com/Nevela-0/PF1-Automate-Damage/assets/235420/7de42c4e-4f9d-47de-a3fa-518ec37297f0)
 
This is on v 0.8 of the mod.

**Comment by Nevela-0** [comment]
Yes, I actually realized it when closing the other issue.
That's the next planned update for healing.
