### ISSUE TITLE
Now automate damage ALWAYS applies critical damage

### ISSUE THREAD

**Issue by R0gu3P403n1x** [Nevela-0/PF1-Automate-Damage#7]
As the title says, now if a critical hit is rolled, clicking apply damage in either the normal entry or the critical damage entry applies critical damage.  If it has to be one way or the other, it is better to have to manually enter in confirmed critical damage.  Thanks for the hard work.

**Comment by Nevela-0** [comment]
I can't reproduce it in version 0.9.2.

If you can give me more details I might be able to check further.

For example, is it a weapon attack? A spell? Maybe a picture.

**Comment by R0gu3P403n1x** [comment]
Is 0.9.3 for v11 of foundry?  It is actually not doing anything when I click on any damage buttons.

**Comment by Nevela-0** [comment]
> Is 0.9.3 for v11 of foundry? It is actually not doing anything when I click on any damage buttons.

I assume you mean pathfinder because there I started the project and still maintain it on foundry v11.
v0.9.3 is for PF1E v10.x
For PF1E v9.x you can use v0.9.2.

I might release backward compatibility in the future but it's not something I'm working on currently.
