### ISSUE TITLE
Damage not working 0.9.3

### ISSUE THREAD

**Issue by R0gu3P403n1x** [Nevela-0/PF1-Automate-Damage#8]
Forge (in case that matters)
Foundry 11.315
PF1 10.2

No other modules installed.  None of the apply damage buttons are doing anything.  Not the basic damage, critical damage, heal or heal half, etc.

**Comment by Nevela-0** [comment]
> Forge (in case that matters) Foundry 11.315 PF1 10.2
> 
> No other modules installed. None of the apply damage buttons are doing anything. Not the basic damage, critical damage, heal or heal half, etc.

I can't reproduce the issue.
Please give more information (what is the damage source? weapon, spell etc)
You can contact me on discord if you'd like.
